### ISSUE TITLE
Async calls

### ISSUE THREAD

**Issue by AleDelSole** [perpetual-mobile/xamarin.piwik#1]
Hi, great project! Is there a way you would recommend (or would you consider adding) to implement async calls? Do you think it's enough to include e.g. TrackEvent and TrackPage within an await Task.Run()?

Thanks!

**Comment by rodja** [comment]
The `TrackEvent()` and `TrackPage()` calls don't need to be async. They do not perform any network activity and hence are very fast. The library is designed to accumulate the users action in a buffer and send them out periodically triggered by a timer.
You can also programmatically trigger the `Dispatch()` method which already is async.
